version: "3"
services:
  mongodb:
    image: mongo:5.0.14
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - main-network

  slack-app-server:
#    image: slack-app:0.0.1-SNAPSHOT
    build: .
    ports:
      - "8081:8081"
    links:
      - mongodb
    restart: on-failure
    depends_on:
      - mongodb
    networks:
     - main-network

networks:
  main-network:
    driver: bridge
