logging.level:
  com.slack.api: DEBUG
server:
  port: 8081
slack:
  token: xoxb-4436422922166-4443334424226-aK99V3bE7KASggNGljYVCj6W
  channel:
    monitor: '#슬랙봇연습'
    general: '#일반'

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/slackbot  # for local
      uri: mongodb://mongodb:27017/slackbot # for docker
      database: slackbot